bridges:
    - channels:
          - type: "mpp"
            id: "âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§"
            channelSettings:
                color: "#222222"
                color2: "#000000"
          - type: "discord"
            id: "1069218861020360775"
          - type: "irc"
            id: "mpp"
